### ISSUE TITLE
Throttle

### ISSUE THREAD

**Issue by KjoeKjoe** [kduma-OSS/L5-CoinHive-api#1]
Hey,

How do you set the throttle of the captcha?

**Comment by kduma** [comment]
There is no throttle. Why would you need?

**Comment by ErSulba** [comment]
maybe for a faster captcha validation, but its ok as long you don't set a ridicolous amount of hashes.

**Comment by kduma** [comment]
@KjoeKjoe, If you want, you can make a Pull Request. I don't have currently time to do that.
